### ISSUE TITLE
Support for TP-Link Archer T2U AC600 USB dual-band wireless adapter?

### ISSUE THREAD

**Issue by waschmi** [kuba-moo/mt7601u#41] opened 2015-11-03 06:37 UTC
I've bought an Archer T2U USB adapter(vendorID 148f, productID 761a)  with MT7610u chip. I thought it would work with mt76 driver but that isn't the case. I was wondering if the mt7601u might work for MT7610u chipset, and if so, how to go about testing this. I'm not experienced at hacking drivers.

(Vendor Source, doesn't work, tho.: http://www.tp-link.com/res/down/soft/Archer_T2U_V1_150901.zip)
(Source that is actually working with that stick: https://github.com/Myria-de/mt7610u_wifi_sta_v3002_dpo_20130916)

**Comment by kuba-moo** [comment] 2015-11-04 22:58
Looks like a duplicate of issue #6 ... Unfortunately I cannot help you. This driver doesn't work for 7610u and there are no plans to extend it.

**Closed as completed by kuba-moo** 2015-11-04 22:58 UTC
