### ISSUE TITLE
Cannot create hotspot connection

### ISSUE THREAD

**Issue by garisha** [kuba-moo/mt7601u#31] opened 2015-08-12 15:32 UTC
Updated to Linux kernel 3.19 on Ubuntu 14.04
Installed the driver without errors. 
Now cannot create hotspot for the device Xiaomi mini wifi usb router; says Ad-hoc mode is not supported by the device.

$iwconfig wlan1
wlan1     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm  
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**Comment by majiancy** [comment] 2015-08-24 07:32
This project is a USB Wifi Dongle Driver only, not the Hotspot one.

**Comment by kuba-moo** [comment] 2015-11-04 23:12
Basically duplicate of issue #4 @majiancy thanks for responding.

**Closed as completed by kuba-moo** 2015-11-04 23:12 UTC
