### ISSUE TITLE
Strange USB Behaviour. ARM imx6.

### ISSUE THREAD

**Issue by sebastianpszczolka** [kuba-moo/mt7601u#79] opened 2019-02-11 14:46 UTC
When I plugged device. 

> usb 1-1: USB disconnect, device number 82
usb 1-1: new full-speed USB device number 83 using ci_hdrc
usb 1-1: new full-speed USB device number 84 using ci_hdrc
usb 1-1: new full-speed USB device number 85 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 85
usb 1-1: new full-speed USB device number 86 using ci_hdrc
usb 1-1: new full-speed USB device number 87 using ci_hdrc
usb 1-1: new full-speed USB device number 88 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 88
usb 1-1: new full-speed USB device number 89 using ci_hdrc
usb 1-1: new full-speed USB device number 90 using ci_hdrc
usb 1-1: new full-speed USB device number 91 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 91
usb 1-1: new full-speed USB device number 92 using ci_hdrc
usb 1-1: new full-speed USB device number 93 using ci_hdrc
usb 1-1: new full-speed USB device number 94 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 94
usb 1-1: new full-speed USB device number 95 using ci_hdrc
usb 1-1: new full-speed USB device number 96 using ci_hdrc
usb 1-1: new full-speed USB device number 97 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 97
usb 1-1: new full-speed USB device number 98 using ci_hdrc
usb 1-1: new full-speed USB device number 99 using ci_hdrc
usb 1-1: new full-speed USB device number 100 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 100
usb 1-1: new full-speed USB device number 101 using ci_hdrc
usb 1-1: new full-speed USB device number 102 using ci_hdrc
usb 1-1: new full-speed USB device number 103 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
random: nonblocking pool is initialized
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 103
usb 1-1: new full-speed USB device number 104 using ci_hdrc
usb 1-1: new full-speed USB device number 105 using ci_hdrc
usb 1-1: new full-speed USB device number 106 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 106
usb 1-1: new full-speed USB device number 107 using ci_hdrc
usb 1-1: new full-speed USB device number 108 using ci_hdrc
usb 1-1: new full-speed USB device number 109 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 109
usb 1-1: new full-speed USB device number 110 using ci_hdrc
usb 1-1: new full-speed USB device number 111 using ci_hdrc
usb 1-1: new full-speed USB device number 112 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 112
usb 1-1: new full-speed USB device number 113 using ci_hdrc
usb 1-1: new full-speed USB device number 114 using ci_hdrc
usb 1-1: new full-speed USB device number 115 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 115
usb 1-1: new full-speed USB device number 116 using ci_hdrc
usb 1-1: new full-speed USB device number 117 using ci_hdrc
usb 1-1: new full-speed USB device number 118 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 118
usb 1-1: new full-speed USB device number 119 using ci_hdrc
usb 1-1: new full-speed USB device number 120 using ci_hdrc
usb 1-1: new full-speed USB device number 121 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 121
usb 1-1: new full-speed USB device number 122 using ci_hdrc
usb 1-1: new full-speed USB device number 123 using ci_hdrc
usb 1-1: new full-speed USB device number 124 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 124
usb 1-1: new full-speed USB device number 125 using ci_hdrc
usb 1-1: new full-speed USB device number 126 using ci_hdrc
usb 1-1: new full-speed USB device number 127 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 127
usb 1-1: new full-speed USB device number 2 using ci_hdrc
usb 1-1: new full-speed USB device number 3 using ci_hdrc
usb 1-1: new full-speed USB device number 4 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 4
usb 1-1: new full-speed USB device number 5 using ci_hdrc
usb 1-1: new full-speed USB device number 6 using ci_hdrc
usb 1-1: new full-speed USB device number 7 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 7
usb 1-1: new full-speed USB device number 8 using ci_hdrc
usb 1-1: new full-speed USB device number 9 using ci_hdrc
usb 1-1: new full-speed USB device number 10 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 10
usb 1-1: new full-speed USB device number 11 using ci_hdrc
usb 1-1: new full-speed USB device number 12 using ci_hdrc
usb 1-1: new full-speed USB device number 13 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 13
usb 1-1: new full-speed USB device number 14 using ci_hdrc
usb 1-1: new full-speed USB device number 15 using ci_hdrc
usb 1-1: new full-speed USB device number 16 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 16
usb 1-1: new full-speed USB device number 17 using ci_hdrc
usb 1-1: new full-speed USB device number 18 using ci_hdrc
usb 1-1: new full-speed USB device number 19 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 19
usb 1-1: new full-speed USB device number 20 using ci_hdrc
usb 1-1: new full-speed USB device number 21 using ci_hdrc
usb 1-1: new full-speed USB device number 22 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 22
usb 1-1: new full-speed USB device number 23 using ci_hdrc
usb 1-1: new full-speed USB device number 24 using ci_hdrc
usb 1-1: new full-speed USB device number 25 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 25
usb 1-1: new full-speed USB device number 26 using ci_hdrc
usb 1-1: new full-speed USB device number 27 using ci_hdrc
usb 1-1: new full-speed USB device number 28 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 28
usb 1-1: new full-speed USB device number 29 using ci_hdrc
usb 1-1: new full-speed USB device number 30 using ci_hdrc
usb 1-1: new full-speed USB device number 31 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 31
usb 1-1: new full-speed USB device number 32 using ci_hdrc
usb 1-1: new full-speed USB device number 33 using ci_hdrc
usb 1-1: new full-speed USB device number 34 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 34
usb 1-1: new full-speed USB device number 35 using ci_hdrc
usb 1-1: new full-speed USB device number 36 using ci_hdrc
usb 1-1: new full-speed USB device number 37 using ci_hdrc
usb 1-1: No LPM exit latency info found, disabling LPM.
usb 1-1: not running at top speed; connect to a high speed hub
mt7601u: probe of 1-1:1.0 failed with error -5
usb 1-1: USB disconnect, device number 37
usb 1-1: new full-speed USB device number 38 using ci_hdrc
usb 1-1: new full-speed USB device number 39 using ci_hdrc
usb 1-1: new high-speed USB device number 40 using ci_hdrc

>
After that messages everything works fine. I do not know what wrong happened.
Greetings

**Comment by kuba-moo** [comment] 2021-02-15 21:01
My guess would be something funny with the platform or the driver is making some assumptions about things being ready before they are ready. Anyway, the issue is old, closing.

**Closed as completed by kuba-moo** 2021-02-15 21:01 UTC
